To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Introducing **Unsloth Studio** - a new open source, no-code web UI to train and run LLMs. [Blog](https://unsloth.ai/docs/new/studio) • [Notebook](https://colab.research.google.com/github/unslothai/unsloth/blob/main/studio/Unsloth_Studio_Colab.ipynb)

<table><tr>
<td align="center"><a href="https://unsloth.ai/docs/new/studio"><img src="https://unsloth.ai/docs/~gitbook/image?url=https%3A%2F%2F3215535692-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FxhOjnexMCB3dmuQFQ2Zq%252Fuploads%252FxV1PO5DbF3ksB51nE2Tw%252Fmore%2520cropped%2520ui%2520for%2520homepage.png%3Falt%3Dmedia%26token%3Df75942c9-3d8d-4b59-8ba2-1a4a38de1b86&width=376&dpr=3&quality=100&sign=a663c397&sv=2" width="200" height="120" alt="Unsloth Studio Training UI"></a><br><sub><b>Train models</b> — no code needed</sub></td>
<td align="center"><a href="https://unsloth.ai/docs/new/studio"><img src="https://unsloth.ai/docs/~gitbook/image?url=https%3A%2F%2F3215535692-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FxhOjnexMCB3dmuQFQ2Zq%252Fuploads%252FRCnTAZ6Uh88DIlU3g0Ij%252Fmainpage%2520unsloth.png%3Falt%3Dmedia%26token%3D837c96b6-bd09-4e81-bc76-fa50421e9bfb&width=376&dpr=3&quality=100&sign=c1a39da1&sv=2" width="200" height="120" alt="Unsloth Studio Chat UI"></a><br><sub><b>Run GGUF models</b> on Mac, Windows & Linux</sub></td>
</tr></table>

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

### Installation

In [1]:
%%capture
import os, re
if "COLAB_" not in "".join(os.environ.keys()):
    !pip install unsloth  # Do this in local & cloud setups
else:
    import torch; v = re.match(r'[\d]{1,}\.[\d]{1,}', str(torch.__version__)).group(0)
    xformers = 'xformers==' + {'2.10':'0.0.34','2.9':'0.0.33.post1','2.8':'0.0.32.post2'}.get(v, "0.0.34")
    !pip install sentencepiece protobuf "datasets==4.3.0" "huggingface_hub>=0.34.0" hf_transfer
    !pip install --no-deps unsloth_zoo bitsandbytes accelerate {xformers} peft trl triton unsloth
!pip install transformers==4.56.2
!pip install --no-deps trl==0.22.2

### Unsloth

In [1]:
from unsloth import FastLanguageModel
import torch

fourbit_models = [
    "unsloth/Qwen3-4B-Instruct-2507-unsloth-bnb-4bit", # Qwen 14B 2x faster
    "unsloth/Qwen3-4B-Thinking-2507-unsloth-bnb-4bit",
    "unsloth/Qwen3-8B-unsloth-bnb-4bit",
    "unsloth/Qwen3-14B-unsloth-bnb-4bit",
    "unsloth/Qwen3-32B-unsloth-bnb-4bit",

    # 4bit dynamic quants for superior accuracy and low memory use
    "unsloth/gemma-3-12b-it-unsloth-bnb-4bit",
    "unsloth/Phi-4",
    "unsloth/Llama-3.1-8B",
    "unsloth/Llama-3.2-3B",
    "unsloth/orpheus-3b-0.1-ft-unsloth-bnb-4bit" # [NEW] We support TTS models!
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "Qwen/Qwen1.5-1.8B",
    max_seq_length = 8192, # Choose any for long context!
    load_in_4bit = True,  # 4 bit quantization to reduce memory
    load_in_8bit = False, # [NEW!] A bit more accurate, uses 2x memory
    full_finetuning = False, # [NEW!] We have full finetuning now!
    # token = "YOUR_HF_TOKEN", # HF Token for gated models
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.4.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Qwen/Qwen1.5-1.8B does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.

We now add LoRA adapters so we only need to update a small amount of parameters!

In [2]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 32, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 32,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

Unsloth 2026.4.4 patched 24 layers with 24 QKV layers, 24 O layers and 24 MLP layers.

<a name="Data"></a>
### Data Prep
We now use the `Qwen-3` format for conversation style finetunes. We use the [Open Math Reasoning](https://huggingface.co/datasets/unsloth/OpenMathReasoning-mini) dataset which was used to win the [AIMO](https://www.kaggle.com/competitions/ai-mathematical-olympiad-progress-prize-2/leaderboard) (AI Mathematical Olympiad - Progress Prize 2) challenge! We sample 10% of verifiable reasoning traces that used DeepSeek R1, and which got > 95% accuracy. Qwen-3 renders multi turn conversations like below:

```
<|im_start|>user
Hello!<|im_end|>
<|im_start|>assistant
Hey there!<|im_end|>

```
We use our `get_chat_template` function to get the correct chat template. We support `zephyr, chatml, mistral, llama, alpaca, vicuna, vicuna_old, phi3, llama3, phi4, qwen2.5, gemma3` and more.

In [3]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "qwen3-thinking",
)

In [4]:
from datasets import load_dataset
dataset = load_dataset("unsloth/OpenMathReasoning-mini", split = "cot")
dataset = dataset.shuffle(seed=42).select(range(200))

We now convert the reasoning dataset into conversational format:

In [5]:
def generate_conversation(examples):
    problems  = examples["problem"]
    solutions = examples["generated_solution"]
    conversations = []
    for problem, solution in zip(problems, solutions):
        conversations.append([
            {"role" : "user",      "content" : problem},
            {"role" : "assistant", "content" : solution},
        ])
    return { "conversations": conversations, }

dataset = dataset.map(generate_conversation, batched = True)

We now have to apply the chat template for `Qwen-3` onto the conversations, and save it to `text`.

In [6]:
def formatting_prompts_func(examples):
   convos = examples["conversations"]
   texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False) for convo in convos]
   return { "text" : texts, }

dataset = dataset.map(formatting_prompts_func, batched = True)

Let's see how the chat template did!

In [7]:
dataset[100]['text']

"<|im_start|>user\nHow many scalene triangles have all sides of integral lengths and a perimeter less than 13?<|im_end|>\n<|im_start|>assistant\n<think>\nOkay, so I need to find the number of scalene triangles with integer side lengths and a perimeter less than 13. Hmm, let's start by recalling what a scalene triangle is. A scalene triangle has all sides of different lengths. Also, the triangle inequality must hold, which states that the sum of the lengths of any two sides must be greater than the third side. And the perimeter has to be less than 13. Alright, let me break this down step by step.\n\nFirst, I should list all possible combinations of three different positive integers (since sides must be integral) where the sum is less than 13. Then, check which of those combinations satisfy the triangle inequality. Since the sides are different, I can assume the sides are in increasing order to avoid counting duplicates. So, let's denote the sides as a, b, c where a < b < c. Then, the perimeter is a + b + c < 13. Also, according to the triangle inequality, a + b > c. Since a < b < c, if a + b > c, the other inequalities (a + c > b and b + c > a) will automatically hold because c is the largest side.\n\nSo, the strategy is to iterate through all possible values of a, b, c with a < b < c, a + b + c < 13, and a + b > c. Then count how many such triplets exist.\n\nLet me start by setting the smallest side a. Since all sides must be at least 1, a starts at 1. Then b has to be greater than a, so starting at a + 1. Then c has to be greater than b, starting at b + 1. But we also have to make sure that a + b > c and the perimeter is less than 13.\n\nLet me try starting with a = 1.\n\nWhen a = 1:\n\nThen b must be at least 2 (since a < b). Let's vary b from 2 upwards, but such that the perimeter is less than 13. Also, c has to be at least b + 1. So let's see.\n\nSo for a =1, b starts at 2:\n\nLet's take b = 2. Then c must be at least 3. Now, the perimeter is 1 + 2 + c < 13 => c < 10. But since a + b > c must hold, 1 + 2 > c => c < 3. But c must be greater than b = 2. So c must be 3. But 1 + 2 = 3, which is not greater than 3. So c cannot be 3. Therefore, there's no triangle with sides 1, 2, 3.\n\nWait, so even if we take c = 3, the perimeter is 1+2+3=6 <13, but 1+2=3 is not greater than 3. So that violates the triangle inequality. Hence, no triangle here.\n\nNext, b = 3. Then c must be at least 4. The perimeter must be less than 13, so 1 + 3 + c <13 => c <9. Also, the triangle inequality requires 1 + 3 > c => c <4. But c must be greater than 3, so c can only be 4. But 1 + 3 = 4, which is equal to c. Not greater. So that doesn't work either. So again, no triangle here.\n\nWait, this seems a pattern. If a =1, then for b >=2, c must be > b, but we need a + b > c. So with a=1, the maximum possible c is a + b -1. But c must be at least b +1. So setting a + b -1 >= b +1 => a -1 >=1 => a >=2. But here a=1, so this doesn't hold. Therefore, there are no triangles with a=1. Because with a=1, the required c would have to be both less than 1 + b and greater than b. Which would imply that 1 + b > c > b. But since c must be an integer, c = b +1. So, 1 + b > b +1 => 1 >1, which is false. Therefore, for a=1, there are no possible scalene triangles. So we can skip a=1.\n\nMoving on to a=2.\n\na=2.\n\nb must be at least 3. Then c must be at least b +1. Let's iterate over possible b and c.\n\nStart with b=3. Then c must be at least 4. Perimeter: 2 + 3 + c <13 => c <8. Also, triangle inequality: 2 + 3 > c => c <5. So c must be >=4 and <5. So c=4. Let's check: sides 2,3,4. Perimeter 9 <13. And 2 + 3 >4 (5>4, which holds). So that's a valid scalene triangle.\n\nNext, b=4. Then c must be at least 5. Perimeter: 2 +4 +c <13 => c <7. Triangle inequality: 2 +4 > c => c <6. So c must be 5. So sides 2,4,5. Perimeter 11 <13. Check 2+4 >5? 6>5, yes. Valid.\n\nb=5. Then c must be at least 6. Perimeter: 2+5 +c <13 => c <6. But c must be >=6 (since c >b=5). Contradiction. So no solution here. So b=5 is invalid.\n\nSo for a=2, b can be 3 and 4, giving two triangles: (2,3,4) and (2,4,5).\n\nNow, a=3.\n\nb must be at least 4. Then c must be at least b +1.\n\nStarting with b=4. c >=5. Perimeter: 3+4 +c <13 => c <6. So c must be 5. Check triangle inequality: 3 +4 >5? 7>5, yes. So triangle (3,4,5). Perimeter 12 <13. Valid.\n\nNext, b=5. Then c must be at least 6. Perimeter: 3+5 +c <13 => c <5. But c >=6, so no solution.\n\nThus, for a=3, only one triangle: (3,4,5).\n\na=4.\n\nb must be at least 5. Then c must be at least 6. Perimeter: 4 +5 +6 =15, which is already >=13. So perimeter would be 15, which is not less than 13. Therefore, no triangles here.\n\nThus, a cannot be 4 or higher, since even the minimal perimeter would be 4 +5 +6=15. So no triangles for a>=4.\n\nSo total triangles so far: 2 (from a=2) +1 (from a=3) =3.\n\nWait, but maybe I missed some? Let's check again.\n\nWait when a=2, b=3, c=4: perimeter 9.\n\na=2, b=4, c=5: perimeter 11.\n\na=3, b=4, c=5: perimeter 12.\n\nAre there any others?\n\nLet me check for a=2, b=5. Wait, earlier for a=2, b=5: perimeter would require c <13 -2 -5 =6, but c >5, so c=6? But 6 is not less than 6. So c can't be 6. Hence, no.\n\nBut maybe another way: Let's check all possible combinations systematically. Maybe we missed a combination where a=2, b=5 is invalid, but maybe a different a?\n\nWait, a=3, b=4, c=5 is okay. What if a=2, b=3, c=5? Let's check.\n\nWait, wait. Wait, if a=2, b=3, c=5. Then a < b < c: 2 <3 <5. Check triangle inequality: 2 +3 >5? 5>5? No, 5 is not greater than 5. So that's invalid. So (2,3,5) is invalid.\n\nSimilarly, if a=2, b=3, c=6: perimeter 11. But 2+3=5 <6. Not valid.\n\nWait, so (2,3,4) is okay. (2,4,5) is okay. (3,4,5) is okay. What about (3,5,6)? Let's check. a=3, b=5, c=6. Then perimeter 14 which is more than 13. So no. How about (2,3,6)? Perimeter 11, but 2+3=5 <6. Not valid.\n\nAlternatively, maybe I need to check all triplets where a + b + c <13 and a < b < c and a + b > c.\n\nAlternatively, perhaps there's a smarter way. Let's list all possible triplets (a, b, c) with a < b < c, a + b + c <13, and a + b > c.\n\nSo let's think of possible perimeters from 6 up to 12, since the minimal perimeter for a scalene triangle is 6 (1,2,3 but that's invalid as before). So maybe perimeters from 6 to 12.\n\nBut let's list all possible scalene triangles with perimeter less than 13.\n\nAlternatively, start by considering possible values of c (the largest side), and find possible a and b.\n\nSince in a scalene triangle, a < b < c, so c must be at least 3 (if a=1, b=2, c=3, but that's perimeter 6, invalid). So starting from c=3 upwards.\n\nBut since perimeter is less than 13, c must be less than 13 - a - b. But since a and b are at least 1 and 2, so c can't be too large.\n\nAlternatively, perhaps let's approach by possible values of c:\n\nFor c=3:\n\nPossible a and b: a < b <3. So a=1, b=2. Then check perimeter 1+2+3=6 <13, but 1+2=3 not greater. Invalid.\n\nc=4:\n\nPossible a < b <4. So possible a=1, b=2; a=1, b=3; a=2, b=3.\n\nCheck each:\n\n1,2,4: 1+2=3 <4. Invalid.\n\n1,3,4: 1+3=4, which is equal. Not greater. Invalid.\n\n2,3,4: 2+3=5 >4. Valid. So that's one.\n\nc=5:\n\nPossible a < b <5. So a=1, b=2; a=1, b=3; a=1, b=4; a=2, b=3; a=2, b=4; a=3, b=4.\n\nCheck each:\n\n1,2,5: 1+2=3 <5. Invalid.\n\n1,3,5: 1+3=4 <5. Invalid.\n\n1,4,5: 1+4=5 =5. Invalid.\n\n2,3,5: 2+3=5 =5. Invalid.\n\n2,4,5: 2+4=6 >5. Valid. So that's another one.\n\n3,4,5: 3+4=7 >5. Valid. Another one.\n\nc=6:\n\nPossible a < b <6.\n\nCheck all combinations where a + b >6 and a + b +6 <13 => a + b <7.\n\nBut since a < b <6, the maximum a + b can be is 5 +4=9. But we need a + b >6 and a + b <7. So a + b must be 7? Wait, because a + b must be greater than 6 and a + b <7. But a and b are integers. So a + b must be 7? Wait, 6 < a + b <7. But since a and b are integers, that would require a + b to be between 6 and 7, but since they are integers, a + b can't be a non-integer. So there are no integer solutions where 6 < a + b <7. Therefore, no triangles with c=6.\n\nWait, but that seems confusing. Let's rephrase: For c=6, the perimeter is a + b +6 <13 => a + b <7. Also, triangle inequality: a + b >6. So 6 < a + b <7. But since a + b must be an integer (as a and b are integers), there's no integer between 6 and 7. Therefore, no such triangles.\n\nSo c=6: no triangles.\n\nc=7:\n\nThen perimeter a + b +7 <13 => a + b <6.\n\nBut triangle inequality a + b >7. So 7 < a + b <6. But that's impossible. So no triangles.\n\nSimilarly, c=8 and higher: a + b would have to be even smaller, making it impossible to satisfy a + b >c. So no triangles for c >=6.\n\nWait, so for c=5, we found two triangles: (2,4,5) and (3,4,5).\n\nFor c=4: (2,3,4).\n\nWait, but earlier when we considered a=3, b=4, c=5, perimeter=12. That's correct.\n\nSo in total, the valid scalene triangles are:\n\n(2,3,4), perimeter 9.\n\n(2,4,5), perimeter 11.\n\n(3,4,5), perimeter 12.\n\nIs that all? Let's check for c=5 again. Are there other combinations?\n\nWait, for a=3, b=4, c=5: yes, that's valid.\n\nBut what about a=2, b=5, c= something? Wait, no, because for a=2, b=5 would require c>5, but perimeter would be 2 +5 +c <13 => c <6. But c>5, so c=6, but 2+5=7 >6. Wait, wait a minute. Wait, if c=6, then perimeter is 13, which is not less than 13, so c=6 would make perimeter 13. So that's excluded. Wait, so 2+5+6=13, which is equal to the limit. But the problem says perimeter less than 13, so 13 is excluded. So (2,5,6) is invalid. So no.\n\nWait, but even if we consider that, triangle inequality: 2 +5 >6? 7 >6, which is true, but the perimeter is 13, which is not allowed.\n\nSo the only valid triangles are the three I listed. Let me check again. Wait, is there a triangle with sides (3,5,6)? Let's see. 3 +5 +6=14 >=13. No. So perimeter is over. How about (3,4,6)? 3 +4 +6=13, also invalid. So no.\n\nWhat about (4,5,6)? Perimeter 15, too big. So no.\n\nHow about (1,2,3): perimeter 6, but triangle inequality fails. (1,2,4): perimeter 7, 1+2=3 <4, invalid. (1,3,4): perimeter 8, 1+3=4, invalid. (1,4,5): perimeter 10, 1+4=5, invalid. (2,3,5): perimeter 10, 2+3=5, invalid. (2,3,6): perimeter 11, 2+3=5 <6, invalid. (2,4,6): perimeter 12, 2+4=6 =6, invalid. (3,4,6): perimeter 13, excluded. (3,5,6): perimeter 14, too big. (4,5,6): 15, too big.\n\nSo yeah, only (2,3,4), (2,4,5), and (3,4,5) are valid. Therefore, the answer is 3.\n\nWait, but hold on, when a=3, b=4, c=5: perimeter 12, which is less than 13. So that's valid. So three triangles.\n\nBut let me check once more for a=2, b=3, c=4: perimeter 9, valid.\n\na=2, b=4, c=5: perimeter 11, valid.\n\na=3, b=4, c=5: perimeter 12, valid.\n\nIs there another combination?\n\nWait, for a=2, b=5, c=6: perimeter 13, invalid. So no.\n\na=2, b=3, c=5: perimeter 10, but 2+3=5, invalid.\n\nWait, a=3, b=5, c=4: but since a < b < c, c must be 5, so no. Wait, no, if a=3, then b must be 4, then c=5. So no others.\n\nThus, the total number is three.\n\nBut wait, in the earlier approach where I considered a=2, b=3,4 and a=3, b=4, that gives 2 +1=3. So seems correct.\n\nBut maybe I missed a triangle where the sides aren't consecutive integers? Let me check.\n\nWait, for example, (2,3,4): consecutive. (2,4,5): not consecutive. Difference of 2 between 2 and 4, then 1 between 4 and 5. (3,4,5): consecutive. Are there any scalene triangles with non-consecutive sides?\n\nFor example, (2,5,6): perimeter 13, invalid. (3,5,7): perimeter 15, too big. (2,3,5): perimeter 10, invalid. (3,4,6): perimeter 13, invalid. (2,5,5): but that's isoceles. Not scalene. So seems like all possibilities are covered.\n\nWait, another check: maybe (3,5,5): isoceles, not scalene. Not allowed.\n\nSo, indeed, only three triangles.\n\nTherefore, the answer should be 3.\n</think>\n\nTo find the number of scalene triangles with integral side lengths and a perimeter less than 13, we need to follow these steps:\n\n1. **Identify the Constraints**:\n   - The sides \\(a\\), \\(b\\), and \\(c\\) must be distinct integers.\n   - The perimeter \\(a + b + c < 13\\).\n   - The triangle inequality must hold: \\(a + b > c\\), \\(a + c > b\\), and \\(b + c > a\\).\n\n2. **Assume \\(a < b < c\\)**:\n   - This ensures all sides are distinct and avoids counting permutations of the same triangle multiple times.\n\n3. **Iterate Through Possible Values of \\(a\\), \\(b\\), and \\(c\\)**:\n   - Start with the smallest possible value for \\(a\\).\n\n4. **Check Each Combination**:\n   - Ensure the perimeter is less than 13.\n   - Ensure the triangle inequality holds.\n\nLet's go through the possible values step-by-step:\n\n### Case 1: \\(a = 2\\)\n- \\(b\\) must be greater than \\(a\\), so \\(b \\geq 3\\).\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 4\\).\n\n#### Subcase 1.1: \\(b = 3\\)\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 4\\).\n- Perimeter constraint: \\(2 + 3 + c < 13 \\Rightarrow c < 8\\).\n- Triangle inequality: \\(2 + 3 > c \\Rightarrow c < 5\\).\n\nThus, \\(c = 4\\):\n- Perimeter: \\(2 + 3 + 4 = 9 < 13\\).\n- Triangle inequality: \\(2 + 3 = 5 > 4\\).\n\nSo, \\((2, 3, 4)\\) is a valid triangle.\n\n#### Subcase 1.2: \\(b = 4\\)\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 5\\).\n- Perimeter constraint: \\(2 + 4 + c < 13 \\Rightarrow c < 7\\).\n- Triangle inequality: \\(2 + 4 > c \\Rightarrow c < 6\\).\n\nThus, \\(c = 5\\):\n- Perimeter: \\(2 + 4 + 5 = 11 < 13\\).\n- Triangle inequality: \\(2 + 4 = 6 > 5\\).\n\nSo, \\((2, 4, 5)\\) is a valid triangle.\n\n#### Subcase 1.3: \\(b = 5\\)\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 6\\).\n- Perimeter constraint: \\(2 + 5 + c < 13 \\Rightarrow c < 6\\).\n\nThere is no valid \\(c\\) since \\(c\\) must be both greater than 5 and less than 6. Hence, no valid triangles in this subcase.\n\n### Case 2: \\(a = 3\\)\n- \\(b\\) must be greater than \\(a\\), so \\(b \\geq 4\\).\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 5\\).\n\n#### Subcase 2.1: \\(b = 4\\)\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 5\\).\n- Perimeter constraint: \\(3 + 4 + c < 13 \\Rightarrow c < 6\\).\n- Triangle inequality: \\(3 + 4 > c \\Rightarrow c < 7\\).\n\nThus, \\(c = 5\\):\n- Perimeter: \\(3 + 4 + 5 = 12 < 13\\).\n- Triangle inequality: \\(3 + 4 = 7 > 5\\).\n\nSo, \\((3, 4, 5)\\) is a valid triangle.\n\n### Case 3: \\(a = 4\\)\n- \\(b\\) must be greater than \\(a\\), so \\(b \\geq 5\\).\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 6\\).\n- Perimeter constraint: \\(4 + 5 + 6 = 15 \\geq 13\\).\n\nThus, no valid triangles in this case since the perimeter exceeds 13.\n\n### Summary of Valid Triangles:\n- \\((2, 3, 4)\\)\n- \\((2, 4, 5)\\)\n- \\((3, 4, 5)\\)\n\nTherefore, the number of scalene triangles with integral side lengths and a perimeter less than 13 is \\(\\boxed{3}\\).<|im_end|>\n"

<a name="Train"></a>
### Train the model
Now let's train our model. We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`.

In [8]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    eval_dataset = None, # Can set up evaluation!
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 4, # Use GA to mimic batch size!
        warmup_steps = 50,
        # num_train_epochs = 5, # Set this for 1 full training run.
        max_steps = 600,
        learning_rate = 2e-4, # Reduce to 2e-5 for long training runs
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.001,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none", # Use TrackIO/WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/200 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

We also use Unsloth's `train_on_completions` method to only train on the assistant outputs and ignore the loss on the user's inputs. This helps increase accuracy of finetunes!

In [9]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<|im_start|>user\n",
    response_part = "<|im_start|>assistant\n",
)

Map (num_proc=6):   0%|          | 0/200 [00:00<?, ? examples/s]

Filter (num_proc=6):   0%|          | 0/200 [00:00<?, ? examples/s]

Let's verify masking the instruction part is done! Let's print the 100th row again.

In [10]:
tokenizer.decode(trainer.train_dataset[0]["input_ids"])

"<|im_start|>user\nHow do you integrate $\\int \\ln{x}\\sin{x}\\ dx$?<|im_end|>\n<|im_start|>assistant\n<think>\nOkay, so I need to integrate the function ln(x) times sin(x) dx. Hmm, let's see. I remember that when you have an integral that's a product of two functions, integration by parts might be useful. The formula for integration by parts is ∫u dv = uv - ∫v du. Right. \n\nFirst, I should decide which part of the integrand to set as u and which as dv. Typically, you want to choose u as the part that becomes simpler when you differentiate it. So here we have ln(x) and sin(x). The derivative of ln(x) is 1/x, which is simpler, and the integral of sin(x) is -cos(x), which doesn't get more complicated. So maybe let u = ln(x) and dv = sin(x) dx.\n\nLet me write that down:\n\nLet u = ln(x) ⇒ du = (1/x) dx\ndv = sin(x) dx ⇒ v = -cos(x)\n\nApplying the integration by parts formula:\n\n∫ ln(x) sin(x) dx = uv - ∫ v du\n= -ln(x) cos(x) - ∫ (-cos(x))(1/x) dx\n= -ln(x) cos(x) + ∫ (cos(x)/x) dx\n\nWait, now I have to compute ∫ cos(x)/x dx. Hmm, that integral doesn't look straightforward. I know that ∫ cos(x)/x dx is related to the cosine integral function, Ci(x), which is a special function and not elementary. But the problem is asking for the integral, and maybe it's expecting an answer in terms of elementary functions? Hmm. \n\nAlternatively, maybe I made a wrong choice of u and dv. Let me try switching them. Suppose I let u = sin(x) and dv = ln(x) dx. Wait, but then dv would be ln(x) dx, and integrating ln(x) dx is x ln(x) - x, which is manageable. Let's try that.\n\nWait, but then if u = sin(x), then du = cos(x) dx, and dv = ln(x) dx, so v = x ln(x) - x. Then the integration by parts would give:\n\nuv - ∫ v du = sin(x)(x ln(x) - x) - ∫ (x ln(x) - x) cos(x) dx\n\nBut that seems more complicated because now the integral becomes ∫ (x ln(x) - x) cos(x) dx, which is even harder than before. That might not help. So maybe the first choice was better.\n\nSo back to the first approach. After integration by parts once, we have:\n\n- ln(x) cos(x) + ∫ cos(x)/x dx\n\nBut ∫ cos(x)/x dx is the cosine integral, Ci(x), plus a constant. But if the problem is expecting an answer in terms of elementary functions, then it's impossible. Wait, but maybe the problem is expecting us to use integration by parts again? Let me think.\n\nWait, can I apply integration by parts again to ∫ cos(x)/x dx? Let's see. Let me set u = 1/x and dv = cos(x) dx. Then du = -1/x² dx, and v = sin(x). Then:\n\n∫ cos(x)/x dx = (1/x) sin(x) - ∫ sin(x) (-1/x²) dx\n= sin(x)/x + ∫ sin(x)/x² dx\n\nHmm, now the integral becomes ∫ sin(x)/x² dx. That's another integral. Let's try integration by parts again for ∫ sin(x)/x² dx.\n\nLet u = 1/x², dv = sin(x) dx\nThen du = -2/x³ dx, v = -cos(x)\n\nSo ∫ sin(x)/x² dx = -cos(x)/x² - ∫ (-cos(x))*(-2/x³) dx\n= -cos(x)/x² - 2 ∫ cos(x)/x³ dx\n\nThis is getting worse. Each time we integrate by parts, the power of x in the denominator increases, but we end up with a more complicated integral. This seems like a dead end. So maybe integrating ∫ cos(x)/x dx isn't possible with elementary functions.\n\nTherefore, maybe the original integral ∫ ln(x) sin(x) dx cannot be expressed in terms of elementary functions and requires special functions like the sine integral (Si(x)) or cosine integral (Ci(x)).\n\nBut the problem is asking to integrate it. Maybe in calculus classes, sometimes they accept answers in terms of these special functions? Or maybe there's another approach?\n\nWait, perhaps if I consider a series expansion. Let me try expanding sin(x) as a Taylor series and then integrate term by term. Hmm. The Taylor series for sin(x) is x - x^3/3! + x^5/5! - x^7/7! + ... So then, multiply by ln(x):\n\nln(x) sin(x) = ln(x) [x - x^3/6 + x^5/120 - x^7/5040 + ...]\n\nThen integrate term by term:\n\n∫ ln(x) sin(x) dx = ∫ [x ln(x) - (x^3 ln(x))/6 + (x^5 ln(x))/120 - ... ] dx\n\nBut integrating each term ∫ x^n ln(x) dx can be done using integration by parts. For each term:\n\nLet’s take the general term: ∫ x^n ln(x) dx\n\nLet u = ln(x) ⇒ du = (1/x) dx\ndv = x^n dx ⇒ v = x^(n+1)/(n+1)\n\nSo, integration by parts gives:\n\nuv - ∫ v du = ln(x) x^(n+1)/(n+1) - ∫ x^(n+1)/(n+1) * (1/x) dx\n= x^(n+1) ln(x)/(n+1) - 1/(n+1) ∫ x^n dx\n= x^(n+1) ln(x)/(n+1) - x^(n+1)/( (n+1)^2 ) + C\n\nTherefore, each term can be integrated. So substituting back into the series:\n\n∫ ln(x) sin(x) dx = ∑ [ (-1)^k / (2k+1)! ) ] [ x^(2k+2) ln(x)/(2k+2) - x^(2k+2)/( (2k+2)^2 ) ] + C\n\nBut this seems like an infinite series, which is not a closed-form expression. So perhaps this is the best we can do, but I'm not sure if that's the expected answer. The problem might be expecting an answer in terms of sine and cosine integrals.\n\nWait, going back to the original integration by parts:\n\n∫ ln(x) sin(x) dx = -ln(x) cos(x) + ∫ cos(x)/x dx\n\nSo if we denote Ci(x) as the cosine integral, which is defined as Ci(x) = -∫_{x}^∞ cos(t)/t dt = γ + ln(x) - ∫_0^x (1 - cos t)/t dt, but in any case, ∫ cos(x)/x dx = Ci(x) + constant. Therefore, the integral can be written as:\n\n- ln(x) cos(x) + Ci(x) + C\n\nBut Ci(x) is a special function, not elementary. So unless the problem allows for the answer in terms of Ci(x), which is sometimes written as Cin(x) or other notations, then that would be the answer. However, if the problem expects an elementary answer, maybe there's a trick I'm missing here.\n\nAlternatively, maybe differentiate the answer to see if we can get back the integrand. Let's check if the derivative of -ln(x) cos(x) + Ci(x) is ln(x) sin(x).\n\nThe derivative of -ln(x) cos(x) is - (1/x) cos(x) + ln(x) sin(x) [using product rule]. Then the derivative of Ci(x) is cos(x)/x. So adding them together:\n\n- (cos(x)/x) + ln(x) sin(x) + cos(x)/x = ln(x) sin(x)\n\nYes, that cancels out the -cos(x)/x and +cos(x)/x terms, leaving ln(x) sin(x). Therefore, the integral is indeed -ln(x) cos(x) + Ci(x) + C.\n\nBut since Ci(x) is a special function, and the problem didn't specify whether to leave it in terms of elementary functions or not, perhaps the answer is expressed using the cosine integral. So the answer is -ln(x) cos(x) + Ci(x) + C.\n\nAlternatively, sometimes the integral ∫ cos(x)/x dx is written as Ci(x), so the answer would be:\n\n- ln(x) cos(x) + Ci(x) + C\n\nBut I need to check if the problem expects the answer in terms of these functions. If not, then perhaps the integral cannot be expressed in terms of elementary functions, and the answer is expressed as above.\n\nSo, summarizing, after integration by parts once, we arrive at an expression involving the cosine integral. Therefore, the integral is:\n\n- ln(x) cos(x) + Ci(x) + C\n\nBut depending on notation, sometimes Ci(x) is defined as ∫_{∞}^{x} cos(t)/t dt, which is equivalent to -∫ cos(x)/x dx. So maybe there's a sign difference. Let me check:\n\nThe standard definition is Ci(x) = -∫_{x}^∞ (cos t)/t dt = γ + ln x - ∫_0^x (1 - cos t)/t dt. Then, the integral ∫ (cos x)/x dx from some lower limit to x would be Ci(x) + constant. Therefore, ∫ (cos x)/x dx = Ci(x) + C.\n\nTherefore, the integral of ln x sin x dx is - ln x cos x + Ci(x) + C.\n\nAlternatively, sometimes people write the cosine integral as Cin(x) or other notations, but I think Ci(x) is standard.\n\nTherefore, unless there is another method, this seems to be the answer.\n\nWait, but maybe there's another approach with integrating factors or some substitution. Let's think. Let me try writing the integral as ∫ ln x sin x dx. Suppose I consider substitution. Let t = x, but that doesn't help. Or maybe let t = ln x, then dt = 1/x dx, but then sin x is still in terms of x. Not helpful.\n\nAlternatively, perhaps tabular integration, but that's essentially integration by parts multiple times. We saw earlier that integrating by parts once leads to the cosine integral, and further integration by parts just leads to more complex integrals.\n\nTherefore, the conclusion is that the integral cannot be expressed in terms of elementary functions and requires the cosine integral function Ci(x). So the answer is:\n\n- ln(x) cos(x) + Ci(x) + C\n\nBut I need to check if there's any mistake in my initial integration by parts. Let me verify the steps again.\n\nLet u = ln x, dv = sin x dx\nThen du = (1/x) dx, v = -cos x\nThen ∫ ln x sin x dx = - ln x cos x + ∫ (cos x)/x dx. That's correct. So the integral of cos x /x dx is Ci(x) + C.\n\nTherefore, the answer is correct.\n\nSo the final answer is written in terms of Ci(x). However, sometimes in math problems, especially in calculus textbooks, if the integral can't be expressed in elementary terms, they might still expect the answer expressed as an unevaluated integral, but in this case, since we did make progress with integration by parts, it's more precise to write it with the cosine integral.\n\nAlternatively, maybe there's a different method? Let me think.\n\nAlternatively, consider differentiation under the integral sign. Let’s think of parameterizing the integral. For example, suppose we consider I(a) = ∫ ln(x) sin(a x) dx, then perhaps differentiate with respect to a. But I'm not sure if that helps. Let's try.\n\nLet I(a) = ∫ ln(x) sin(a x) dx\n\nThen dI/da = ∫ ln(x) x cos(a x) dx\n\nBut integrating that would involve ∫ x ln(x) cos(a x) dx, which seems more complicated. Maybe not helpful.\n\nAlternatively, perhaps consider integrating sin x as the derivative of -cos x. But that's what we already did.\n\nAlternatively, express ln x in integral form. For example, ln x = ∫_1^x (1/t) dt. Then substitute into the original integral:\n\n∫ [ ∫_1^x (1/t) dt ] sin x dx\n\nBut swapping the order of integration might not be straightforward. Let's consider:\n\n∫ ln x sin x dx = ∫ ( ∫_1^x 1/t dt ) sin x dx\n\nThen by changing the order of integration. The region of integration is t from 1 to x, and x is integrated over. Let’s visualize this as a double integral over t and x. The region is 1 ≤ t ≤ x, and x goes from, say, some lower limit to upper limit. If we switch the order, t ranges from 1 to infinity (assuming the upper limit is infinity, but in an indefinite integral, this might not be applicable). Hmm, maybe not helpful.\n\nAlternatively, perhaps differentiation: Let’s suppose we let F(x) = ∫ ln x sin x dx. Then maybe find a differential equation for F(x). Compute F’(x) = ln x sin x. Hmm, that's not helpful, since it just gives the integrand back.\n\nAlternatively, consider expressing sin x as imaginary part of e^{ix}. So, sin x = Im(e^{ix}), so ∫ ln x sin x dx = Im ∫ ln x e^{ix} dx. Maybe integrating ∫ ln x e^{ix} dx.\n\nLet me try that. Let’s compute ∫ ln x e^{ix} dx.\n\nLet u = ln x ⇒ du = 1/x dx\ndv = e^{ix} dx ⇒ v = -i e^{ix}\n\nIntegration by parts gives:\n\n- i e^{ix} ln x - ∫ (-i e^{ix})(1/x) dx\n= -i e^{ix} ln x + i ∫ e^{ix}/x dx\n\nNow, ∫ e^{ix}/x dx is the exponential integral function, Ei(i x), another special function. So this approach also leads to special functions. The integral ∫ e^{ix}/x dx is related to Ei(i x), which is expressed in terms of Ci(x) and Si(x) as Ei(i x) = Ci(x) + i Si(x) - i π/2 for x > 0.\n\nTherefore, the integral becomes:\n\n- i e^{ix} ln x + i (Ci(x) + i Si(x) - i π/2) + C\n\nBut simplifying, this would involve trigonometric integrals again. Taking the imaginary part to get back to the original integral involving sin x:\n\nIm [ -i e^{ix} ln x + i (Ci(x) + i Si(x) - i π/2) ]\n\nLet’s compute each term. First, -i e^{ix} ln x. The imaginary part of -i e^{ix} ln x is -i * [cos x + i sin x] ln x. The imaginary part would be -i * cos x ln x (which is imaginary) and -i * i sin x ln x = sin x ln x (real). Wait, but the entire expression is multiplied by -i. Wait, maybe better to write e^{ix} = cos x + i sin x, so:\n\n- i e^{ix} ln x = -i (cos x + i sin x) ln x = -i cos x ln x + sin x ln x\n\nTherefore, the imaginary part of this term is -i cos x ln x (which is purely imaginary) plus sin x ln x (real). Since we are taking the imaginary part of the entire expression, the real parts are disregarded. So the imaginary part here would be the coefficient of the i term. Wait, no, the expression is:\n\nIm [ (-i e^{ix} ln x) + i (Ci(x) + i Si(x) - i π/2) ]\n\nLet me handle each part:\n\nFirst term: Im [ -i e^{ix} ln x ] = Im [ -i (cos x + i sin x) ln x ] = Im [ -i cos x ln x + sin x ln x ] = -cos x ln x (since -i cos x ln x is the imaginary part, coefficient of i is -cos x ln x, and sin x ln x is real, so the imaginary part is -cos x ln x)\n\nSecond term: Im [ i (Ci(x) + i Si(x) - i π/2) ] = Im [ i Ci(x) - Si(x) - (i^2) π/2 ] = Im [ i Ci(x) - Si(x) + π/2 ] = Ci(x) (since the term i Ci(x) has imaginary part Ci(x), and -Si(x) and π/2 are real)\n\nTherefore, combining both parts:\n\nIm [ ... ] = -cos x ln x + Ci(x) \n\nHence, the original integral ∫ ln x sin x dx = -cos x ln x + Ci(x) + C\n\nWhich matches the earlier result. So this confirms the answer.\n\nTherefore, the integral is -ln x cos x + Ci(x) + C.\n\nThus, the final answer should be written in terms of the cosine integral function. However, if the problem expects the answer in terms of elementary functions, it's impossible. But since the problem just asks to integrate, I think expressing it with Ci(x) is acceptable. So the answer is:\n\n\\boxed{ -\\ln(x) \\cos(x) + \\text{Ci}(x) + C }\n</think>\n\nTo integrate \\(\\int \\ln{x} \\sin{x} \\, dx\\), we use integration by parts. We choose \\(u = \\ln{x}\\) and \\(dv = \\sin{x} \\, dx\\). Then, we have:\n\n\\[\ndu = \\frac{1}{x} \\, dx \\quad \\text{and} \\quad v = -\\cos{x}\n\\]\n\nApplying the integration by parts formula \\(\\int u \\, dv = uv - \\int v \\, du\\), we get:\n\n\\[\n\\int \\ln{x} \\sin{x} \\, dx = -\\ln{x} \\cos{x} - \\int -\\cos{x} \\cdot \\frac{1}{x} \\, dx\n\\]\n\nSimplifying the integral on the right-hand side, we have:\n\n\\[\n\\int \\ln{x} \\sin{x} \\, dx = -\\ln{x} \\cos{x} + \\int \\frac{\\cos{x}}{x} \\, dx\n\\]\n\nThe remaining integral \\(\\int \\frac{\\cos{x}}{x} \\, dx\\) is the cosine integral function, denoted \\(\\text{Ci}(x)\\). Therefore, the integral evaluates to:\n\n\\[\n\\int \\ln{x} \\sin{x} \\, dx = -\\ln{x} \\cos{x} + \\text{Ci}(x) + C\n\\]\n\nThus, the final answer is:\n\n\\[\n\\boxed{-\\ln(x) \\cos(x) + \\text{Ci}(x) + C}\n\\]<|im_end|>\n"

Now let's print the masked out example - you should see only the answer is present:

In [11]:
tokenizer.decode([tokenizer.pad_token_id if x == -100 else x for x in trainer.train_dataset[100]["labels"]]).replace(tokenizer.pad_token, " ")

"                            <think>\nOkay, so I need to find the number of scalene triangles with integer side lengths and a perimeter less than 13. Hmm, let's start by recalling what a scalene triangle is. A scalene triangle has all sides of different lengths. Also, the triangle inequality must hold, which states that the sum of the lengths of any two sides must be greater than the third side. And the perimeter has to be less than 13. Alright, let me break this down step by step.\n\nFirst, I should list all possible combinations of three different positive integers (since sides must be integral) where the sum is less than 13. Then, check which of those combinations satisfy the triangle inequality. Since the sides are different, I can assume the sides are in increasing order to avoid counting duplicates. So, let's denote the sides as a, b, c where a < b < c. Then, the perimeter is a + b + c < 13. Also, according to the triangle inequality, a + b > c. Since a < b < c, if a + b > c, the other inequalities (a + c > b and b + c > a) will automatically hold because c is the largest side.\n\nSo, the strategy is to iterate through all possible values of a, b, c with a < b < c, a + b + c < 13, and a + b > c. Then count how many such triplets exist.\n\nLet me start by setting the smallest side a. Since all sides must be at least 1, a starts at 1. Then b has to be greater than a, so starting at a + 1. Then c has to be greater than b, starting at b + 1. But we also have to make sure that a + b > c and the perimeter is less than 13.\n\nLet me try starting with a = 1.\n\nWhen a = 1:\n\nThen b must be at least 2 (since a < b). Let's vary b from 2 upwards, but such that the perimeter is less than 13. Also, c has to be at least b + 1. So let's see.\n\nSo for a =1, b starts at 2:\n\nLet's take b = 2. Then c must be at least 3. Now, the perimeter is 1 + 2 + c < 13 => c < 10. But since a + b > c must hold, 1 + 2 > c => c < 3. But c must be greater than b = 2. So c must be 3. But 1 + 2 = 3, which is not greater than 3. So c cannot be 3. Therefore, there's no triangle with sides 1, 2, 3.\n\nWait, so even if we take c = 3, the perimeter is 1+2+3=6 <13, but 1+2=3 is not greater than 3. So that violates the triangle inequality. Hence, no triangle here.\n\nNext, b = 3. Then c must be at least 4. The perimeter must be less than 13, so 1 + 3 + c <13 => c <9. Also, the triangle inequality requires 1 + 3 > c => c <4. But c must be greater than 3, so c can only be 4. But 1 + 3 = 4, which is equal to c. Not greater. So that doesn't work either. So again, no triangle here.\n\nWait, this seems a pattern. If a =1, then for b >=2, c must be > b, but we need a + b > c. So with a=1, the maximum possible c is a + b -1. But c must be at least b +1. So setting a + b -1 >= b +1 => a -1 >=1 => a >=2. But here a=1, so this doesn't hold. Therefore, there are no triangles with a=1. Because with a=1, the required c would have to be both less than 1 + b and greater than b. Which would imply that 1 + b > c > b. But since c must be an integer, c = b +1. So, 1 + b > b +1 => 1 >1, which is false. Therefore, for a=1, there are no possible scalene triangles. So we can skip a=1.\n\nMoving on to a=2.\n\na=2.\n\nb must be at least 3. Then c must be at least b +1. Let's iterate over possible b and c.\n\nStart with b=3. Then c must be at least 4. Perimeter: 2 + 3 + c <13 => c <8. Also, triangle inequality: 2 + 3 > c => c <5. So c must be >=4 and <5. So c=4. Let's check: sides 2,3,4. Perimeter 9 <13. And 2 + 3 >4 (5>4, which holds). So that's a valid scalene triangle.\n\nNext, b=4. Then c must be at least 5. Perimeter: 2 +4 +c <13 => c <7. Triangle inequality: 2 +4 > c => c <6. So c must be 5. So sides 2,4,5. Perimeter 11 <13. Check 2+4 >5? 6>5, yes. Valid.\n\nb=5. Then c must be at least 6. Perimeter: 2+5 +c <13 => c <6. But c must be >=6 (since c >b=5). Contradiction. So no solution here. So b=5 is invalid.\n\nSo for a=2, b can be 3 and 4, giving two triangles: (2,3,4) and (2,4,5).\n\nNow, a=3.\n\nb must be at least 4. Then c must be at least b +1.\n\nStarting with b=4. c >=5. Perimeter: 3+4 +c <13 => c <6. So c must be 5. Check triangle inequality: 3 +4 >5? 7>5, yes. So triangle (3,4,5). Perimeter 12 <13. Valid.\n\nNext, b=5. Then c must be at least 6. Perimeter: 3+5 +c <13 => c <5. But c >=6, so no solution.\n\nThus, for a=3, only one triangle: (3,4,5).\n\na=4.\n\nb must be at least 5. Then c must be at least 6. Perimeter: 4 +5 +6 =15, which is already >=13. So perimeter would be 15, which is not less than 13. Therefore, no triangles here.\n\nThus, a cannot be 4 or higher, since even the minimal perimeter would be 4 +5 +6=15. So no triangles for a>=4.\n\nSo total triangles so far: 2 (from a=2) +1 (from a=3) =3.\n\nWait, but maybe I missed some? Let's check again.\n\nWait when a=2, b=3, c=4: perimeter 9.\n\na=2, b=4, c=5: perimeter 11.\n\na=3, b=4, c=5: perimeter 12.\n\nAre there any others?\n\nLet me check for a=2, b=5. Wait, earlier for a=2, b=5: perimeter would require c <13 -2 -5 =6, but c >5, so c=6? But 6 is not less than 6. So c can't be 6. Hence, no.\n\nBut maybe another way: Let's check all possible combinations systematically. Maybe we missed a combination where a=2, b=5 is invalid, but maybe a different a?\n\nWait, a=3, b=4, c=5 is okay. What if a=2, b=3, c=5? Let's check.\n\nWait, wait. Wait, if a=2, b=3, c=5. Then a < b < c: 2 <3 <5. Check triangle inequality: 2 +3 >5? 5>5? No, 5 is not greater than 5. So that's invalid. So (2,3,5) is invalid.\n\nSimilarly, if a=2, b=3, c=6: perimeter 11. But 2+3=5 <6. Not valid.\n\nWait, so (2,3,4) is okay. (2,4,5) is okay. (3,4,5) is okay. What about (3,5,6)? Let's check. a=3, b=5, c=6. Then perimeter 14 which is more than 13. So no. How about (2,3,6)? Perimeter 11, but 2+3=5 <6. Not valid.\n\nAlternatively, maybe I need to check all triplets where a + b + c <13 and a < b < c and a + b > c.\n\nAlternatively, perhaps there's a smarter way. Let's list all possible triplets (a, b, c) with a < b < c, a + b + c <13, and a + b > c.\n\nSo let's think of possible perimeters from 6 up to 12, since the minimal perimeter for a scalene triangle is 6 (1,2,3 but that's invalid as before). So maybe perimeters from 6 to 12.\n\nBut let's list all possible scalene triangles with perimeter less than 13.\n\nAlternatively, start by considering possible values of c (the largest side), and find possible a and b.\n\nSince in a scalene triangle, a < b < c, so c must be at least 3 (if a=1, b=2, c=3, but that's perimeter 6, invalid). So starting from c=3 upwards.\n\nBut since perimeter is less than 13, c must be less than 13 - a - b. But since a and b are at least 1 and 2, so c can't be too large.\n\nAlternatively, perhaps let's approach by possible values of c:\n\nFor c=3:\n\nPossible a and b: a < b <3. So a=1, b=2. Then check perimeter 1+2+3=6 <13, but 1+2=3 not greater. Invalid.\n\nc=4:\n\nPossible a < b <4. So possible a=1, b=2; a=1, b=3; a=2, b=3.\n\nCheck each:\n\n1,2,4: 1+2=3 <4. Invalid.\n\n1,3,4: 1+3=4, which is equal. Not greater. Invalid.\n\n2,3,4: 2+3=5 >4. Valid. So that's one.\n\nc=5:\n\nPossible a < b <5. So a=1, b=2; a=1, b=3; a=1, b=4; a=2, b=3; a=2, b=4; a=3, b=4.\n\nCheck each:\n\n1,2,5: 1+2=3 <5. Invalid.\n\n1,3,5: 1+3=4 <5. Invalid.\n\n1,4,5: 1+4=5 =5. Invalid.\n\n2,3,5: 2+3=5 =5. Invalid.\n\n2,4,5: 2+4=6 >5. Valid. So that's another one.\n\n3,4,5: 3+4=7 >5. Valid. Another one.\n\nc=6:\n\nPossible a < b <6.\n\nCheck all combinations where a + b >6 and a + b +6 <13 => a + b <7.\n\nBut since a < b <6, the maximum a + b can be is 5 +4=9. But we need a + b >6 and a + b <7. So a + b must be 7? Wait, because a + b must be greater than 6 and a + b <7. But a and b are integers. So a + b must be 7? Wait, 6 < a + b <7. But since a and b are integers, that would require a + b to be between 6 and 7, but since they are integers, a + b can't be a non-integer. So there are no integer solutions where 6 < a + b <7. Therefore, no triangles with c=6.\n\nWait, but that seems confusing. Let's rephrase: For c=6, the perimeter is a + b +6 <13 => a + b <7. Also, triangle inequality: a + b >6. So 6 < a + b <7. But since a + b must be an integer (as a and b are integers), there's no integer between 6 and 7. Therefore, no such triangles.\n\nSo c=6: no triangles.\n\nc=7:\n\nThen perimeter a + b +7 <13 => a + b <6.\n\nBut triangle inequality a + b >7. So 7 < a + b <6. But that's impossible. So no triangles.\n\nSimilarly, c=8 and higher: a + b would have to be even smaller, making it impossible to satisfy a + b >c. So no triangles for c >=6.\n\nWait, so for c=5, we found two triangles: (2,4,5) and (3,4,5).\n\nFor c=4: (2,3,4).\n\nWait, but earlier when we considered a=3, b=4, c=5, perimeter=12. That's correct.\n\nSo in total, the valid scalene triangles are:\n\n(2,3,4), perimeter 9.\n\n(2,4,5), perimeter 11.\n\n(3,4,5), perimeter 12.\n\nIs that all? Let's check for c=5 again. Are there other combinations?\n\nWait, for a=3, b=4, c=5: yes, that's valid.\n\nBut what about a=2, b=5, c= something? Wait, no, because for a=2, b=5 would require c>5, but perimeter would be 2 +5 +c <13 => c <6. But c>5, so c=6, but 2+5=7 >6. Wait, wait a minute. Wait, if c=6, then perimeter is 13, which is not less than 13, so c=6 would make perimeter 13. So that's excluded. Wait, so 2+5+6=13, which is equal to the limit. But the problem says perimeter less than 13, so 13 is excluded. So (2,5,6) is invalid. So no.\n\nWait, but even if we consider that, triangle inequality: 2 +5 >6? 7 >6, which is true, but the perimeter is 13, which is not allowed.\n\nSo the only valid triangles are the three I listed. Let me check again. Wait, is there a triangle with sides (3,5,6)? Let's see. 3 +5 +6=14 >=13. No. So perimeter is over. How about (3,4,6)? 3 +4 +6=13, also invalid. So no.\n\nWhat about (4,5,6)? Perimeter 15, too big. So no.\n\nHow about (1,2,3): perimeter 6, but triangle inequality fails. (1,2,4): perimeter 7, 1+2=3 <4, invalid. (1,3,4): perimeter 8, 1+3=4, invalid. (1,4,5): perimeter 10, 1+4=5, invalid. (2,3,5): perimeter 10, 2+3=5, invalid. (2,3,6): perimeter 11, 2+3=5 <6, invalid. (2,4,6): perimeter 12, 2+4=6 =6, invalid. (3,4,6): perimeter 13, excluded. (3,5,6): perimeter 14, too big. (4,5,6): 15, too big.\n\nSo yeah, only (2,3,4), (2,4,5), and (3,4,5) are valid. Therefore, the answer is 3.\n\nWait, but hold on, when a=3, b=4, c=5: perimeter 12, which is less than 13. So that's valid. So three triangles.\n\nBut let me check once more for a=2, b=3, c=4: perimeter 9, valid.\n\na=2, b=4, c=5: perimeter 11, valid.\n\na=3, b=4, c=5: perimeter 12, valid.\n\nIs there another combination?\n\nWait, for a=2, b=5, c=6: perimeter 13, invalid. So no.\n\na=2, b=3, c=5: perimeter 10, but 2+3=5, invalid.\n\nWait, a=3, b=5, c=4: but since a < b < c, c must be 5, so no. Wait, no, if a=3, then b must be 4, then c=5. So no others.\n\nThus, the total number is three.\n\nBut wait, in the earlier approach where I considered a=2, b=3,4 and a=3, b=4, that gives 2 +1=3. So seems correct.\n\nBut maybe I missed a triangle where the sides aren't consecutive integers? Let me check.\n\nWait, for example, (2,3,4): consecutive. (2,4,5): not consecutive. Difference of 2 between 2 and 4, then 1 between 4 and 5. (3,4,5): consecutive. Are there any scalene triangles with non-consecutive sides?\n\nFor example, (2,5,6): perimeter 13, invalid. (3,5,7): perimeter 15, too big. (2,3,5): perimeter 10, invalid. (3,4,6): perimeter 13, invalid. (2,5,5): but that's isoceles. Not scalene. So seems like all possibilities are covered.\n\nWait, another check: maybe (3,5,5): isoceles, not scalene. Not allowed.\n\nSo, indeed, only three triangles.\n\nTherefore, the answer should be 3.\n</think>\n\nTo find the number of scalene triangles with integral side lengths and a perimeter less than 13, we need to follow these steps:\n\n1. **Identify the Constraints**:\n   - The sides \\(a\\), \\(b\\), and \\(c\\) must be distinct integers.\n   - The perimeter \\(a + b + c < 13\\).\n   - The triangle inequality must hold: \\(a + b > c\\), \\(a + c > b\\), and \\(b + c > a\\).\n\n2. **Assume \\(a < b < c\\)**:\n   - This ensures all sides are distinct and avoids counting permutations of the same triangle multiple times.\n\n3. **Iterate Through Possible Values of \\(a\\), \\(b\\), and \\(c\\)**:\n   - Start with the smallest possible value for \\(a\\).\n\n4. **Check Each Combination**:\n   - Ensure the perimeter is less than 13.\n   - Ensure the triangle inequality holds.\n\nLet's go through the possible values step-by-step:\n\n### Case 1: \\(a = 2\\)\n- \\(b\\) must be greater than \\(a\\), so \\(b \\geq 3\\).\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 4\\).\n\n#### Subcase 1.1: \\(b = 3\\)\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 4\\).\n- Perimeter constraint: \\(2 + 3 + c < 13 \\Rightarrow c < 8\\).\n- Triangle inequality: \\(2 + 3 > c \\Rightarrow c < 5\\).\n\nThus, \\(c = 4\\):\n- Perimeter: \\(2 + 3 + 4 = 9 < 13\\).\n- Triangle inequality: \\(2 + 3 = 5 > 4\\).\n\nSo, \\((2, 3, 4)\\) is a valid triangle.\n\n#### Subcase 1.2: \\(b = 4\\)\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 5\\).\n- Perimeter constraint: \\(2 + 4 + c < 13 \\Rightarrow c < 7\\).\n- Triangle inequality: \\(2 + 4 > c \\Rightarrow c < 6\\).\n\nThus, \\(c = 5\\):\n- Perimeter: \\(2 + 4 + 5 = 11 < 13\\).\n- Triangle inequality: \\(2 + 4 = 6 > 5\\).\n\nSo, \\((2, 4, 5)\\) is a valid triangle.\n\n#### Subcase 1.3: \\(b = 5\\)\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 6\\).\n- Perimeter constraint: \\(2 + 5 + c < 13 \\Rightarrow c < 6\\).\n\nThere is no valid \\(c\\) since \\(c\\) must be both greater than 5 and less than 6. Hence, no valid triangles in this subcase.\n\n### Case 2: \\(a = 3\\)\n- \\(b\\) must be greater than \\(a\\), so \\(b \\geq 4\\).\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 5\\).\n\n#### Subcase 2.1: \\(b = 4\\)\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 5\\).\n- Perimeter constraint: \\(3 + 4 + c < 13 \\Rightarrow c < 6\\).\n- Triangle inequality: \\(3 + 4 > c \\Rightarrow c < 7\\).\n\nThus, \\(c = 5\\):\n- Perimeter: \\(3 + 4 + 5 = 12 < 13\\).\n- Triangle inequality: \\(3 + 4 = 7 > 5\\).\n\nSo, \\((3, 4, 5)\\) is a valid triangle.\n\n### Case 3: \\(a = 4\\)\n- \\(b\\) must be greater than \\(a\\), so \\(b \\geq 5\\).\n- \\(c\\) must be greater than \\(b\\), so \\(c \\geq 6\\).\n- Perimeter constraint: \\(4 + 5 + 6 = 15 \\geq 13\\).\n\nThus, no valid triangles in this case since the perimeter exceeds 13.\n\n### Summary of Valid Triangles:\n- \\((2, 3, 4)\\)\n- \\((2, 4, 5)\\)\n- \\((3, 4, 5)\\)\n\nTherefore, the number of scalene triangles with integral side lengths and a perimeter less than 13 is \\(\\boxed{3}\\).<|im_end|>\n"

In [12]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = Tesla T4. Max memory = 14.563 GB.
1.988 GB of memory reserved.

Let's train the model! To resume a training run, set `trainer.train(resume_from_checkpoint = True)`

In [ ]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 19,252 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 66,060,288 of 4,088,528,384 (1.62% trained)
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

Unsloth: Will smartly offload gradients to save VRAM!

In [13]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 200 | Num Epochs = 12 | Total steps = 600
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 4 x 1) = 4
 "-____-"     Trainable parameters = 29,982,720 of 1,866,811,392 (1.61% trained)

Unsloth: Will smartly offload gradients to save VRAM!

In [14]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

7929.4355 seconds used for training.
132.16 minutes used for training.
Peak reserved memory = 7.094 GB.
Peak reserved memory for training = 5.106 GB.
Peak reserved memory % of max memory = 48.712 %.
Peak reserved memory for training % of max memory = 35.061 %.

<a name="Inference"></a>
### Inference
Let's run the model via Unsloth native inference! According to the `Qwen-3` team, the recommended settings for instruct inference are `temperature = 0.7, top_p = 0.8, top_k = 20`

For reasoning chat based inference, `temperature = 0.6, top_p = 0.95, top_k = 20`

In [21]:
messages = [
    {"role" : "user", "content" : "Identify even numbers in the list : [1,2.2,3.1,4.22]"}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize = False,
    add_generation_prompt = True, # Must add for generation
    enable_thinking = False, # Disable thinking
)

im_end_id = tokenizer.convert_tokens_to_ids("<|im_end|>")

from transformers import TextStreamer
_ = model.generate(
    **tokenizer(text, return_tensors = "pt").to("cuda"),
    max_new_tokens = 8192, # Increase for longer outputs!
    # temperature = 0, top_p = 0.8, top_k = 20, # For non thinking
    do_sample=False,                  # better than temperature=0
    eos_token_id=im_end_id,           # stop at first <|im_end|>
    pad_token_id=im_end_id,
    streamer=TextStreamer(tokenizer, skip_prompt=False),
)

Okay, so I need to find even numbers in the list [1, 2, 3, 4]. Hmm, let's see. First, I remember that even numbers are multiples of 2. Since 2 is the second-smallest prime number, right? So the even numbers in the list would be even multiples of 2. Let me check that idea again. Let's take the number 2. 2 is even, and 2*2=4 is a multiple of 2. That works. How about 4? 4 is even, 4/2=2. So those two are even numbers. Now, what about the other numbers? Let's see, 1 is odd, and 1*2=2, which isn't even. 3 is odd, 3 is odd, 3*2=6 is even, that's okay. 4 is even, 4 is okay. So so far, the even numbers are 2 and 4. That seems to be the only even number in the list. Let me verify by looking at the original list again. 1, 2, 3, 4. The even numbers are 2 and 4. Let me list them all again: 2, 4. That seems right. So the answer should be 2 and 4.
Wait, but maybe I missed something. Let me think again. The problem says to find even numbers, which are those that are a multiple of 2. So even numbers are numbers that can be formed with 2, like 2, 4, 6, etc. So 2, 4, 6, 8, 10, etc. But 1 is odd, not even. So the answer is 2 and 4. That's the conclusion I arrive at after checking all the multiples of 2 in the list.
I think that's it. Let me just make sure there aren't any other even numbers. The list starts from 1 up to 4. So 2 and 4 are the only even numbers. So the answer is 2 and 4.
</think>

To identify even numbers in the list \([1, 2, 3, 4]\), we need to determine the even multiples of 2 in the list. An even number is a multiple of 2. A multiple of 2 can be expressed as \(2k\), where \(k\) is a positive integer. Therefore, the even numbers in the list are the even multiples of 2.

Let's go through the list:
- \(1\) is an odd number.
- \(2\) is even.
- \(3\) is odd.
- \(4\) is even.

Thus, the even numbers in the list are:
\[
2, 4
\]

Let's verify these numbers:
- \(2 = 2 \times 1\).
- \(4 = 4 \times 1\).
- \(\text{all other numbers} \) are odd, and their multiples are even.

Therefore, the even numbers in the list \([1, 2, 3, 4]\) are:
\[
\boxed{2, 4}
\]<|im_end|>

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Hugging Face's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [ ]:
model.save_pretrained("qwen_lora")  # Local saving
tokenizer.save_pretrained("qwen_lora")
# model.push_to_hub("your_name/qwen_lora", token = "YOUR_HF_TOKEN") # Online saving
# tokenizer.push_to_hub("your_name/qwen_lora", token = "YOUR_HF_TOKEN") # Online saving

('lora_model/tokenizer_config.json',
 'lora_model/special_tokens_map.json',
 'lora_model/chat_template.jinja',
 'lora_model/vocab.json',
 'lora_model/merges.txt',
 'lora_model/added_tokens.json',
 'lora_model/tokenizer.json')

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [ ]:
if False:
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "qwen_lora", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = 2048,
        load_in_4bit = True,
    )

### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [ ]:
# Merge to 16bit
if False:
    model.save_pretrained_merged("qwen_finetune_16bit", tokenizer, save_method = "merged_16bit",)
if False: # Pushing to HF Hub
    model.push_to_hub_merged("HF_USERNAME/qwen_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "YOUR_HF_TOKEN")

# Merge to 4bit
if False:
    model.save_pretrained_merged("qwen_finetune_4bit", tokenizer, save_method = "merged_4bit",)
if False: # Pushing to HF Hub
    model.push_to_hub_merged("HF_USERNAME/qwen_finetune_4bit", tokenizer, save_method = "merged_4bit", token = "YOUR_HF_TOKEN")

# Just LoRA adapters
if False:
    model.save_pretrained("qwen_lora")
    tokenizer.save_pretrained("qwen_lora")
if False: # Pushing to HF Hub
    model.push_to_hub("HF_USERNAME/qwen_lora", token = "YOUR_HF_TOKEN")
    tokenizer.push_to_hub("HF_USERNAME/qwen_lora", token = "YOUR_HF_TOKEN")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [docs page](https://unsloth.ai/docs/basics/inference-and-deployment/saving-to-gguf)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

Likewise, if you want to instead push to GGUF to your Hugging Face account, set `if False` to `if True` and add your Hugging Face token and upload location!

In [ ]:
# Save to 8bit Q8_0
if False:
    model.save_pretrained_gguf("qwen_finetune", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False:
    model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, token = "YOUR_HF_TOKEN")

# Save to 16bit GGUF
if False:
    model.save_pretrained_gguf("qwen_finetune", tokenizer, quantization_method = "f16")
if False: # Pushing to HF Hub
    model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, quantization_method = "f16", token = "YOUR_HF_TOKEN")

# Save to q4_k_m GGUF
if False:
    model.save_pretrained_gguf("qwen_finetune", tokenizer, quantization_method = "q4_k_m")
if False: # Pushing to HF Hub
    model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, quantization_method = "q4_k_m", token = "YOUR_HF_TOKEN")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "HF_USERNAME/qwen_finetune", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "YOUR_HF_TOKEN", # Get a token at https://huggingface.co/settings/tokens
    )

Now, use the `qwen_finetune.Q8_0.gguf` file or `qwen_finetune.Q4_K_M.gguf` file in llama.cpp.

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
4. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://unsloth.ai/docs/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

  This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).